insert into tb_state(id, name, uf) values (1, 'Acre', 'AC');
insert into tb_state(id, name, uf) values (2, 'Alagoas', 'AL');
insert into tb_state(id, name, uf) values (3, 'Amazonas', 'AM');
insert into tb_state(id, name, uf) values (4, 'Amapá', 'AP');
insert into tb_state(id, name, uf) values (5, 'Bahia', 'BA');
insert into tb_state(id, name, uf) values (6, 'Ceará', 'CE');
insert into tb_state(id, name, uf) values (7, 'Distrito Federal', 'DF');
insert into tb_state(id, name, uf) values (8, 'Espírito Santo', 'ES');
insert into tb_state(id, name, uf) values (9, 'Goiás', 'GO');
insert into tb_state(id, name, uf) values (10, 'Maranhão', 'MA');
insert into tb_state(id, name, uf) values (11, 'Minas Gerais', 'MG');
insert into tb_state(id, name, uf) values (12, 'Mato Grosso do Sul', 'MS');
insert into tb_state(id, name, uf) values (13, 'Mato Grosso', 'MT');
insert into tb_state(id, name, uf) values (14, 'Pará', 'PA');
insert into tb_state(id, name, uf) values (15, 'Paraíba', 'PB');
insert into tb_state(id, name, uf) values (16, 'Pernambuco', 'PE');
insert into tb_state(id, name, uf) values (17, 'Piauí', 'PI');
insert into tb_state(id, name, uf) values (18, 'Paraná', 'PR');
insert into tb_state(id, name, uf) values (19, 'Rio de Janeiro', 'RJ');
insert into tb_state(id, name, uf) values (20, 'Rio Grande do Norte', 'RN');
insert into tb_state(id, name, uf) values (21, 'Rondônia', 'RO');
insert into tb_state(id, name, uf) values (22, 'Roraima', 'RR');
insert into tb_state(id, name, uf) values (23, 'Rio Grande do Sul', 'RS');
insert into tb_state(id, name, uf) values (24, 'Santa Catarina', 'SC');
insert into tb_state(id, name, uf) values (25, 'Sergipe', 'SE');
insert into tb_state(id, name, uf) values (26, 'São Paulo', 'SP');
insert into tb_state(id, name, uf) values (27, 'Tocantins', 'TO');
insert into tb_state(id, name, uf) values (99, 'Exterior', 'EX');